Repository GDSC-NITH/CookBook-Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#2 Updated README.md
  README.md
  assets/textWidgetOutputFlutter.png
Labels: documentation, Hacktoberfest-Accepted

#3 ReactJs Text
  .DS_Store
  ReactJs/component.md
  assets/OutputOne.png
  assets/OutputTwo.png
Labels: Hacktoberfest-Accepted

#5 added RecyclerView features
  Android using Kotlin/RecyclerView.md
  Android using Kotlin/assets/image-1.png
  Android using Kotlin/assets/image-2.png
  Android using Kotlin/assets/image-3.png
Labels: enhancement, Hacktoberfest-Accepted

#11 Bubble Sort Added
  Cpp/Algorithms/Bubble Sort/bubbleSort.md
  Kotlin(Android)/RecyclerView.md
  Kotlin(Android)/assets/image-1.png
  Kotlin(Android)/assets/image-2.png
  Kotlin(Android)/assets/image-3.png
Labels: Hacktoberfest, Hacktoberfest-Accepted

#12 Added button and done few changes
  Flutter/Button/text_button.md
Labels: Hacktoberfest-Accepted

#18 Added quicksort algorithm
  Cpp/Algorithms/QuickSort/quicksort.md
Labels: Hacktoberfest-Accepted

#16 Floating Action Button
  Flutter/Button/floating_action_button.md
  Flutter/Button/icon_button.md
Labels: good first issue, Hacktoberfest

#14 added BFS Algorithm
  Graph/BFS.md
Labels: Hacktoberfest

#9 Optimised spaces
  Tailwind CSS/Text/tailwind.md
Labels: Hacktoberfest-Accepted

#20 Added DropDown Button
  Flutter/Button/dropdown_button.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#21 Networking Fundamentals
  Google Cloud Platform(GCP)/Network Fundamentals/Network.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#25 Open CV Fundamentals
  Open CV/readme.md
Labels: Hacktoberfest

#27 Deep Learning
  Deep Learning/readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#31 Web-Development-Concepts-Explained-in-great-detail
  Important topics of C/Pointers.md
  OOPS/Principles-of-OOPS.md
  Web-Development/Web-Dev-Basics.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#26 Binary Search Added
  Cpp/Algorithms/Binary Search/binarySeach.md
Labels: Hacktoberfest

#30 added dfs
  Cpp/Algorithms/Depth First Search/dfs.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#28 Added Bucket sort
  Cpp/Algorithms/Bucket sort/bucketsort.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#34 WebD Folder Image issue fix
  Web-Development/assets/.DS_Store
  Web-Development/assets/OutputOne.png
  Web-Development/assets/OutputTwo.png
Labels: Hacktoberfest, Hacktoberfest-Accepted

#35 fix React
  Web-Development/ReactJs/Text/component.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#36 Sorting Technique
  CPP/Kotlin/bubbleSort.kt
  CPP/Kotlin/insertionSort.kt
  CPP/Kotlin/mergeSort.kt
  CPP/Kotlin/selectionSort.kt
Labels: good first issue, Hacktoberfest-Accepted

#39 Added Queue Data Structure
  Queue/queue.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#24 Added Kadane's Algorithm
  Cpp/Algorithms/Kadane's Algorithm/Kadane's Algo.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#52 Create DFS.md
  Graph/DFS.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#54 Added independent Topics
  Deep Learning/Independent Topics/readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#55 Create Design Thinking.md
  UI & UX/Design Thinking.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#56 Machine Learning topics
  Machine Learning/readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#50 React Router dom v6.4.2
  Web-Development/ReactJs/Text/ReactRouter.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#51 Buttons in Jetpack Compose
  Kotlin(Android)/Jetpack Compose/buttons.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#47 fix: Images are not loading.
  Kotlin(Android)/RecyclerView.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-Accepted

#46 added Heap Sort
  Cpp/Algorithms/Heap Sort/Heap Sort.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#43 Selection Sort Algorithm
  Cpp/Algorithms/Selection-Sort/selection-sort.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#37 added
  Important topics of C/structure.md
Labels: Hacktoberfest-Accepted, minor changes

#57 Sliding window algorithm
  Cpp/Algorithms/Sliding Window/SlidingWindow.md
Labels: enhancement, Hacktoberfest, Hacktoberfest-Accepted

#58 Adding Tower of Hanoi Algorithm
  Cpp/Algorithms/Recursion/Tower of Hanoi.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#49 added Radix sort
  Cpp/Algorithms/Radix sort/Radix sort.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#44 added Queue
  Cpp/Algorithms/Queue/queue.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#61 Added DBMS concepts
  Database Management System/introduction.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#59 Create DatePicker.md
  Kotlin(Android)/DatePicker.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#62 Icon Button
  Flutter/Button/icon_button.md
Labels: enhancement, Hacktoberfest, Hacktoberfest-Accepted

#65 add Golang
  Golang/Golang.md
Labels: enhancement, Hacktoberfest, Hacktoberfest-Accepted

#66 add cpp.md
  Cpp/cpp.md
Labels: documentation, Hacktoberfest, Hacktoberfest-Accepted

#63 Text Button
  Flutter/Button/text_button.md
Labels: review

#67 Update bubbleSort.md
  Cpp/Algorithms/Bubble Sort/bubbleSort.md
Labels: documentation

#69 Created Python.md
  Python/python.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#70 topological sort for graph
  Graph/topological-sort.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#68 Binary Search Tree
  Cpp/BinarySeacrhTree.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#74 algorithm for MST Kruskal’s Minimum Spanning Tree Algorithm
  Graph/Kruskal's Algorithm.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#76 Linked List Data Structure
  .DS_Store
  Cpp/.DS_Store
  Cpp/Data Structures/BinarySeacrhTree.md
  Cpp/Data Structures/LinkedList.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#83 Created htmlcodes.md
  Web-Development/htmlcodes.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#82 Updated TimePicker.md
  Kotlin(Android)/TimePicker.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#80 Update Buttons md files
  Flutter/Button/inkwell_button.md
  Flutter/Button/popup_menubutton.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#84 Stack Data Structure
  .DS_Store
  Cpp/.DS_Store
  Cpp/Data Structures/.DS_Store
  Cpp/Data Structures/Binary Search Tree/.DS_Store
  Cpp/Data Structures/Binary Search Tree/BinarySeacrhTree.md
  Cpp/Data Structures/Linked List Data Structure/.DS_Store
  Cpp/Data Structures/Linked List Data Structure/LinkedList.md
  Cpp/Data Structures/Stack Data Structure/stack.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#85 Queue Data Structure
  Cpp/Data Structures/Queue Data Structure/Queue.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#89 Hash Table
  Cpp/Data Structures/Hash Table/HashTable.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#79 Added DNF Sort.
  Cpp/Algorithms/DNF Sort/README.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#77 added Graph's Algorithams
  CPP/Kotlin/StringToData.kt
  CPP/Kotlin/helloWorld.kt
  Graph/Kruskal's_Algorithm.md
  Graph/MST.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#88 Created Pointers.md
  Cpp/Pointers.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#92 new file flutter image widget
  Flutter/Image/image_widget.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#99 Usability Testing
  UI & UX/Usability Testing.md
  UI & UX/Usability Testing1.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#93 Updated The Markdown Format & Updated Some Codes
  Cpp/Algorithms/Sliding Window/SlidingWindow.md
  Cpp/Pointers.md
  Cpp/cpp.md
  Database Management System/introduction.md
  Deep Learning/Independent Topics/readme.md
  Deep Learning/readme.md
  Flutter/Button/inkwell_button.md
  Flutter/Button/popup_menubutton.md
  Flutter/Text/text_widget.md
  Golang/Golang.md
  Google Cloud Platform(GCP)/Network Fundamentals/Network.md
  Graph/BFS.md
  Graph/DFS.md
  Graph/Kruskal's Algorithm.md
  Graph/topological-sort.md
  Important topics of C/Pointers.md
  Important topics of C/structure.md
  Kotlin(Android)/DatePicker.md
  Kotlin(Android)/Jetpack Compose/buttons.md
  Kotlin(Android)/RecyclerView.md
  Machine Learning/readme.md
  OOPS/Principles-of-OOPS.md
  Open CV/readme.md
  Python/python.md
  UI & UX/Design Thinking.md
  Web-Development/Backend Web Development/django-rest-framework.md
  Web-Development/ReactJs/Text/ReactRouter.md
  Web-Development/ReactJs/Text/component.md
  Web-Development/Web-Dev-Basics.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#101 Create object-tracking.md
  Open CV/object-tracking.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#75 prim's algorithm
  Graph/Kruskal's Algorithm.md
  Graph/prim's algorithm.md
  Open CV/object-tracking.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#102 time complexity cpp
  Cpp/timeComplexity.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#90 Create Css-flexbox.md
  Web-Development/Css-flexbox.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#103 Create vector
  Cpp/vector
Labels: Hacktoberfest, Hacktoberfest-Accepted

#106 Bootstrap docs
  Cpp/Data Structures/.DS_Store
  Web-Development/Bootstrap/Bootstrap.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#107 Created java.md
  Java/java.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#86 Create Google-Cloud-Concepts.md
  Google Cloud Platform(GCP)/Network Fundamentals/Google-Cloud-Concepts.md
Labels: Hacktoberfest, Hacktoberfest-Accepted, review

#115 Create newsAPI
  Web-Development/newsAPI/public/index.html
  Web-Development/newsAPI/public/styles.css
  Web-Development/newsAPI/src/app.js
  Web-Development/newsAPI/src/index.js
Labels: Hacktoberfest, Hacktoberfest-Accepted

#112 Create functions.md
  Web-Development/Js/functions.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#111 Added MySQL connector cheatsheet
  Database Management System/mysql-connector.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#117 Inheritance concept.md
  OOPS/Inheritance in Java/Inheritance_JAVA.md
Labels: documentation, Hacktoberfest, Hacktoberfest-Accepted

#114 Create Constructors-Destructors
  Cpp/Constructors-Destructors.md
  Cpp/Preprocessors.md
Labels: good first issue, Hacktoberfest, Hacktoberfest-Accepted

#71 Add Backend Web APIs Project
  Backend-Web-APIs/app.js
  Backend-Web-APIs/index.html
  Backend-Web-APIs/style.css
Labels: Hacktoberfest, Hacktoberfest-Accepted

#125 Update java.md
  Java/java.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#135 template.md
  Cpp/template.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#129 added a figma.md file
  UI & UX/figma.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#120 Create DataTypes.md
  Cpp/DataTypes.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#132 Added more information about Horizontal navbar with an active link
  Web-Development/navbar-using-css.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#130 Updated value of mid variable
  Cpp/Algorithms/Binary Search/binarySeach.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#147 Create Heaps
  Cpp/Data Structures/Heaps.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#149 Added Strings.md in CPP Directory
  Cpp/Strings.md
  Web-Development/Backend Web Development/NodeJS.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#113 Added Dataset for ML and Data Analysis
  Machine Learning/Datasets/Dataset.md
  Machine Learning/Datasets/readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted

#161 Create ejs.md
  Web-Development/ejs.md
Labels: add-on-data

#160 Added bubble sort program in java
  Java/Arraylist.java
  Java/Bubblesort.java
Labels: Hacktoberfest, Hacktoberfest-Accepted

#128 added a new file of backtracking
  Backtracking/Backtracking introduction.md
Labels: good first issue, Hacktoberfest
